export const apiKey = "b148cceefb18438989a113003260705";

export const weatherImages = {
  "Partly cloudy": require("../assets/images/partlycloudy.png"),
  "Moderate rain": require("../assets/images/moderaterain.png"),
  "Patchy rain possible": require("../assets/images/moderaterain.png"),
  Sunny: require("../assets/images/sun.png"),
  Clear: require("../assets/images/sun.png"),
  Overcast: require("../assets/images/cloud.png"),
  Cloudy: require("../assets/images/cloud.png"),
  "Light rain": require("../assets/images/moderaterain.png"),
  "Moderate rain at times": require("../assets/images/moderaterain.png"),
  "Heavy rain": require("../assets/images/heavyrain.png"),
  "Heavy rain at times": require("../assets/images/heavyrain.png"),
  "Moderate or heavy freezing rain": require("../assets/images/heavyrain.png"),
  "Moderate or heavy rain shower": require("../assets/images/heavyrain.png"),
  "Moderate or heavy rain with thunder": require("../assets/images/heavyrain.png"),
  "Mostly cloudy": require("../assets/images/cloud.png"),
  Mist: require("../assets/images/cloud.png"),
  Fog: require("../assets/images/cloud.png"),
  "Freezing fog": require("../assets/images/cloud.png"),
  "Patchy light rain": require("../assets/images/moderaterain.png"),
  "Light drizzle": require("../assets/images/moderaterain.png"),
  "Thundery outbreaks possible": require("../assets/images/heavyrain.png"),
  "Patchy snow possible": require("../assets/images/cloud.png"),
  Blizzard: require("../assets/images/heavyrain.png"),
  "Patchy rain nearby": require("../assets/images/moderaterain.png"),
  other: require("../assets/images/moderaterain.png"),
};
